# 📡 PDS Engineering: Git Ping Action
# ===================================
#
# This is a GitHub action that:
# • Pings a remote repository on GitHub
# • (By submitting an empty commit)
# • And noting else!

---

name: '✅ PDS Engineering: PDS Validate'
author: 'Jordan Padams <jordan.h.padams@jpl.nasa.gov>'
branding:
  icon: 'flag'
  color: 'blue'

inputs:
  datapath:
    description: |
      Absolute path to PDS4 XML labels and associated data to validate
    required: true
  schemas:
    description: |
      Path(s) to schemas to use for validation. By default, validate will use the schemas specified in the PDS4 labels.
    required: false
  schematrons:
    description: |
      Path(s) to schematrons to use for validation. By default, validate will use the schemas specified in the PDS4 labels.
    required: false
  skip_content_validation:
    description: |
      Flag to disable data product content validation. This checks the actual bits in the data product match the XML specification. By default, this is enabled.
    required: false
    default: 'false'
  failure_expected:
    description: |
      Flag to specify that validation failure is expected. This is intended for failure regression test cases.
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.datapath}}
    - ${{inputs.pds4_version}}
    - ${{inputs.release}}

