# 📡 PDS Engineering: Git Ping Action
# ===================================
#
# This is a GitHub action that:
# • Pings a remote repository on GitHub
# • (By submitting an empty commit)
# • And noting else!

---

name: '📡 PDS Engineering: PDS Validate'
author: 'Jordan Padams <jordan.h.padams@jpl.nasa.gov>'
branding:
  icon: 'flag'
  color: 'blue'
inputs:
  dirpath:
    description: >
      Absolute path to data to validate
    required: true
  pds4_version:
    description: >
      PDS4 Information Model Version. Defaults to the latest version. Use the semantic version, e.g. 1.14.0.0
    required: false
    default: 'latest'
  release: >
      Flag to specify if this is intended as a release or a development build. Expected values: true, false
    required: false
    default: 'false'
  # token:
  #   description: >
  #     A GitHub personal access token that can be used to commit to the target repository. You can generate
  #     such a token by visiting the your account's "Settings" → "Developer settings"  → "Personal access
  #     tokens" and clicking "Generate new token"; save this token in the target repository's "Secrets".
  #     section.
  #   required: true
  # branch:
  #   description: >
  #     The name of the branch to which to send the empty or "ping" commit. By default it will be the
  #     `master` branch.
  #   required: false
  #   default: 'master'
  # message:
  #   description: >
  #     The commit message. This should contain a description of why the "ping" or empty-commit trigger is
  #     being made. If not given, it defaults to the word `Ping` plus an appropriate emoji.
  #   required: false
  #   default: '📡 Ping'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.dirpath}}
    - ${{inputs.pds4_version}}
    - ${{inputs.release}}

...
